const ROLES = Object.freeze({
  STUDENT: 'STUDENT',
  EMPLOYER: 'EMPLOYER',
  ADMIN: 'ADMIN',
});

const JOB_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  FILLED: 'FILLED',
  CANCELLED: 'CANCELLED',
});

const APPLICATION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  REVIEWING: 'REVIEWING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN',
});

const PAYMENT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
});

const PAYMENT_CURRENCY = Object.freeze({
  INR: 'INR',
});

const NOTIFICATION_TYPES = Object.freeze({
  APPLICATION_ACCEPTED: 'APPLICATION_ACCEPTED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  NEW_MESSAGE: 'NEW_MESSAGE',
  JOB_APPROVED: 'JOB_APPROVED',
  JOB_REJECTED: 'JOB_REJECTED',
  NEW_JOB_NEARBY: 'NEW_JOB_NEARBY',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  EMPLOYER_APPROVED: 'EMPLOYER_APPROVED',
  ACCOUNT_VERIFIED: 'ACCOUNT_VERIFIED',
});

const JOB_TYPES = Object.freeze({
  FULL_TIME: 'FULL_TIME',
  PART_TIME: 'PART_TIME',
  INTERNSHIP: 'INTERNSHIP',
  CONTRACT: 'CONTRACT',
  FREELANCE: 'FREELANCE',
});

const EXPERIENCE_LEVELS = Object.freeze({
  ENTRY: 'ENTRY',
  INTERMEDIATE: 'INTERMEDIATE',
  MID: 'MID',
  SENIOR: 'SENIOR',
});

const GENDERS = Object.freeze({
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
  PREFER_NOT_TO_SAY: 'PREFER_NOT_TO_SAY',
});

const JOB_POSTING_FEE = parseInt(process.env.JOB_POSTING_FEE || '99', 10);

const CURRENCY = process.env.CURRENCY || 'INR';

const PAGINATION = Object.freeze({
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
});

const UPLOAD = Object.freeze({
  MAX_FILE_SIZE: parseInt(process.env.MAX_FILE_SIZE || '5242880', 10),
  ALLOWED_MIME_TYPES: (process.env.ALLOWED_MIME_TYPES ||
    'image/jpeg,image/png,image/webp,application/pdf'
  ).split(','),
});

const OT_EXPIRY_MINUTES = 10;

const REFRESH_TOKEN_EXPIRY_DAYS = 7;

module.exports = {
  ROLES,
  JOB_STATUS,
  APPLICATION_STATUS,
  PAYMENT_STATUS,
  PAYMENT_CURRENCY,
  NOTIFICATION_TYPES,
  JOB_TYPES,
  EXPERIENCE_LEVELS,
  GENDERS,
  JOB_POSTING_FEE,
  CURRENCY,
  PAGINATION,
  UPLOAD,
  OT_EXPIRY_MINUTES,
  REFRESH_TOKEN_EXPIRY_DAYS,
};
